### ISSUE TITLE
Some font clipping at certain sizes

### ISSUE THREAD

**Issue by jamesmunns** [wezm/profont#6]
Hey, I put together a quick font demo to look at various sizes, and realized that when printing "Hello, world!" at all of the supported sizes, the `w` and `o` overlapped at the 24 and 7 point font sizes. This caused the rightmost column of the `w` to be overwritten with the background color.

For 24 point font, this wasn't too noticeable, but at 7 point it causes the `w` to look more like a `u` with a tail.

I'll take some photos of this on an epaper display later today (once I have daylight).

Repro code:

```rust
// 24 point
let _ = Text::new("Hello, world!", Point::new(24, 24))
    .into_styled(text_style!(
        font = profont::ProFont24Point,
        text_color = White,
        background_color = Black
    ))
    .draw(&mut display);

// 7 point
let _ = Text::new("Hello, world!", Point::new(24, 100))
    .into_styled(text_style!(
        font = profont::ProFont7Point { },
        text_color = White,
        background_color = Black
    ))
    .draw(&mut display);
```

(also, unrelated, for the 7 point font, I needed to create a unit struct, which wasn't necessary at other sizes. Let me know if you want a separate issue for that)

**Comment by wezm** [comment]
Oh looks like the unit struct snuck in in a previous upgrade, definitely shouldn't be different to the others.

I can see what you mean about the `w` in the specimens in the README. I'd noticed the W at 24pt before but not the 7 pt one. I'll need to dig into the source font a bit and see why it's happening.
